#!/bin/sh
pet_path=/usr/bin/pet
pet_path/pet-update -c -nc

dbname="pet"
username="pet"

psql $dbname $username << EOF
INSERT INTO team (name, maintainer, url) VALUES ('pkg-perl', 'Debian Perl Group <pkg-perl-maintainers@list.alioth.debian.org>', 'http://pkg-perl.alioth.debian.org/');

INSERT INTO repository (name, type, root, web_root, team_id) VALUES ('git', 'git', 'https://pet.alioth.debian.org/pet2-data/pkg-perl/git-pkg-perl-packages.json', 'http://anonscm.debian.org/gitweb/?p=pkg-perl/packages', 1);

INSERT INTO package (name, repository_id) VALUES ('clive', 1);

INSERT INTO archive (name, url, web_root) VALUES ('debian', 'http://cdn.debian.net/debian', 'http://packages.qa.debian.org')

INSERT INTO suite (archive_id, name) VALUES (1, 'unstable');

\q
EOF
